version: '3'

services:
  # サービス名
  django:
    build:
      context: ./containers    # Dockerfileがあるディレクトリまでの相対パス
      dockerfile: Dockerfile.prod   # Dockerfileのファイル名

    # 作成するコンテナ名の指定
    container_name: django

    # 使用するポートの設定
    ports:
      - "8000:8000"

    # 対話的なセッションやコマンドラインの操作を許可する
    tty: true

    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - ${SRC_PATH}:/root/workspace

    # コンテナ起動時に実行されるコマンド
    # gunicorn を起動する前に migrate を自動実行
    command: sh -c "python manage.py migrate && gunicorn closet_search.wsgi:application --bind 0.0.0.0:8000"
