version: '3'

services:
  # Django アプリケーション
  django:
    build:
      context: ./containers
      dockerfile: Dockerfile.dev
    container_name: django
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ${SRC_PATH}:/root/workspace

    #初回のみ
    #(但し今後マイグレーションでエラーが起きたら、2回目以降の部分をコメントアウトアウトしてこちらに切り替えて対応してください。)
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"

    #2回目以降は以下のようにしてOK
    #command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  # MySQL データベース
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
