version: '3'

services:
  # サービス名
  django:
    build:
      context: ./containers    # Dockerfileがあるディレクトリまでの相対パス
      dockerfile: Dockerfile.prod   # Dockerfileのファイル名

    # 作成するコンテナ名の指定
    container_name: django

    # 使用するポートの設定
    ports:
      - "8000:8000"

    # 対話的なセッションやコマンドラインの操作を許可する
    tty: true

    volumes:
      # ホストの Django プロジェクト（${SRC_PATH}）をコンテナ内の /root/workspace にマウント
      # manage.py やアプリケーションコードにアクセスできるようにするために必須
      - ${SRC_PATH}:/root/workspace

    # 環境変数ファイルの指定
    env_file:
      - .env
