name: Auto Deploy to style-log.com (Docker Compose)

on:
  push:
    branches:
      - main  # mainブランチのみ自動デプロイ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHubのリポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH接続のため秘密鍵を設定
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # 3. サーバーでデプロイ処理を実行
      - name: Deploy to server (with Docker Compose)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            set -e  # エラーが発生したらスクリプトを停止

            echo ">>> Move to project directory"
            cd /home/ec2-user/closet-search

            echo ">>> Fetching latest code from main branch"
            git fetch --all
            git reset --hard origin/main

            echo ">>> Building and restarting Docker containers"
            # 旧コンテナを停止してから再ビルド＆起動
            sudo docker compose down
            sudo docker compose up --build -d

            echo ">>> Deployment completed!"
          EOF
