# プルリクエストが作成されたときに Mattermost に通知を送るワークフロー
name: Notify Mattermost on PR to develop # ファイルの目的がわかるように記載

on: # 処理の起動条件を定義
  pull_request:
    types: [opened]         # プルリクエストが「作成された時」のみ
    branches:
      - develop             # 対象ブランチが develop の場合に限定

jobs: # 実行するジョブ（処理の単位）
  notify: # ジョブの名前（任意）
    runs-on: ubuntu-latest # GitHub が提供する Ubuntu の最新ランナー上で実行

    steps: # ジョブ内で実行する手順を定義
      - name: Send message to Mattermost # Step の名前（UI に表示される）
        run: |
          # Mattermost に POST リクエストを送信（JSON 形式）
          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"text\": \"プルリクエストが作成されたのでご確認ください！\\n\
●リポジトリ: ${{ github.repository }}\\n\
●PRタイトル: ${{ github.event.pull_request.title }}\\n\
●作成者: ${{ github.event.pull_request.user.login }}\\n\
●URL: ${{ github.event.pull_request.html_url }}\"
          }" \
          ${{ secrets.MATTERMOST_WEBHOOK }} # Webhook URL は GitHub Secrets に保存
