name: Notify Mattermost on PR to develop # ファイルの目的がわかるように記載

on: # 処理の起動条件を定義

pull_request:

types: [opened] # プルリクエストがオープン（作成）

branches:

- develop # ターゲットブランチがdevelopブランチ

jobs: # ジョブの定義

notify: # 「notify」はジョブの名前（何でもOK）

runs-on: ubuntu-latest # GitHubが提供する最新のUbuntu環境（仮想マシン） 上で実行

steps: # 処理の中身を定義

- name: Send message to Mattermost

run: |

curl -X POST -H 'Content-Type: application/json' \

-d '{

"text": "プルリクエストが作成されたのでご確認ください！\n●リポジトリ: '${{ github.repository }}'\n●PRタイトル: ${{ github.event.pull_request.title }}\n●作成者: ${{ github.event.pull_request.user.login }}\n●URL: ${{ github.event.pull_request.html_url }}"

}' ${{ secrets.MATTERMOST_WEBHOOK }}
